//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassDescription
    {
        public int id { get; set; }
        public string Course_Number { get; set; }
        public string Course_Name { get; set; }
        public string Instructor { get; set; }
        public string Office_Hours { get; set; }
        public int Semester { get; set; }
        public string Email { get; set; }
        public string Office { get; set; }
    }
}
