//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class class_tracker
    {
        public int id { get; set; }
        public string course { get; set; }
        public string semester { get; set; }
        public string date_due { get; set; }
        public string importance { get; set; }
    }
}
