//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassTracker.Models
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;

    public partial class DueItem
    {
        public int id { get; set; }
        public string Class { get; set; }
        public System.DateTime Date_Due { get; set; }
        public string Semester { get; set; }
        public string Importance { get; set; }
        public string Description { get; set; }
        public string Date_Due_Formatted
        {
            get
            {
                return Date_Due.ToLongDateString();
            }
            set
            {
                var dateTime = DateTime.ParseExact(value, "D", CultureInfo.CurrentCulture);
                Date_Due = dateTime;
            }
        }

        /// <summary>
        /// This is used to set the row of the colours, depending on when the item is due, the colour reflects the urgency
        /// </summary>
        public int DueSoon
        {
            get
            {
                var difference = (Date_Due - DateTime.Now).TotalDays;

                if (difference <= -1)
                {
                    //The Item is Overdue
                    return 0;
                }
                else if (difference < 4)
                {
                    //The Item is Urgent
                    return 1;
                }
                else if (difference < 7)
                {
                    //The Item is SomeWhat Urgent
                    return 2;
                }
                else
                {
                    //The Item has no Urgency
                    return 3;
                }
            }
        }
    }
}
