//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassTracker.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Linq;

    public partial class DueItem
    {
        public int id { get; set; }
        public string Class { get; set; }
        public System.DateTime Date_Due { get; set; }
        public string Semester { get; set; }
        public string Importance { get; set; }
        public string Description { get; set; }
    }
}
